phys-memory-base = "0x4200_0000"
phys-memory-size = "0x800_0000"  # 128M
kernel-base-paddr = "0x4200_0000"
kernel-base-vaddr = "0xffff_ff80_4200_0000"
mmio-regions = [
    ["0xfec0_0000", "0x1000"],   # IO APIC
    ["0xfed0_0000", "0x1000"],   # HPET
    ["0xfee0_0000", "0x1000"],   # Local APIC
]
