[package]
name = "ratio"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "The type of ratios and related operations"
license = "GPL-3.0-or-later OR Apache-2.0"
homepage = "https://github.com/rcore-os/arceos"
repository = "https://github.com/rcore-os/arceos/tree/main/crates/ratio"
documentation = "https://rcore-os.github.io/arceos/ratio/index.html"

[dependencies]
